#!/bin/zsh
set -e

BASEDIR=$(dirname "$0")
SOFTWARES_DIR="${SOFTWARES_DIR:-$HOME/.softwares}"

SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/zlib-1.3.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/cmake-3.30.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/ninja-1.12.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/mozilla-ca-2024.07.02.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/openssl-3.3.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/xz-5.6.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/Python-3.12.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/bzip2-1.0.8.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/pcre2-10.44.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/swig-4.2.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/z3-4.13.0.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/lz4-1.10.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/zstd-1.5.6.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/ncurses-6.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/libedit-3.1.2024.08.08.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/libffi-3.4.6.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/icu4c-75.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/readline-8.2.13.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/libiconv-1.17.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/libxml2-2.13.3.sh
SOFTWARES_DIR=$SOFTWARES_DIR TEMP=1 $BASEDIR/llvm-18.1.8.sh