#!/bin/zsh
set -e

BASEDIR=$(dirname "$0")
SOFTWARES_DIR="${SOFTWARES_DIR:-$HOME/.softwares}"

SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libiconv-1.17.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/pkg-config-0.29.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libressl-3.9.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/zlib-1.3.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/ncurses-6.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/texinfo-7.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/m4-1.4.19.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/bison-3.8.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libedit-3.1.2024.08.08.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/krb5-1.21.3.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libxcrypt-4.4.36.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/cyrus-sasl-2.1.28.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/openldap-2.6.8.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/c-ares-1.33.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/jemalloc-5.3.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/xz-5.6.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/icu4c-75.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/readline-8.2.13.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/sqlite-3.46.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/util-linux-2.40.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libffi-3.4.6.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/gettext-0.22.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libtirpc-1.3.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libnsl-2.0.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/tcl-tk-8.6.14.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/gdbm-1.24.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libb2-0.98.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/bzip2-1.0.8.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/openssl-3.3.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/Python-3.12.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libxml2-2.13.3.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libev-4.33.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/nghttp2-1.63.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libidn2-2.3.7.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libssh2-1.11.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/brotli-1.1.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/nghttp3-1.5.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/ngtcp2-1.7.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/lz4-1.10.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/zstd-1.5.6.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/curl-8.9.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/cmake-3.30.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/ninja-1.12.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/z3-4.13.0.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/pcre2-10.44.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/swig-4.2.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/llvm-18.1.8.sh


#SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/setuptools-73.0.0.sh
#SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/meson-1.5.1.sh