#!/bin/zsh
set -e

BASEDIR=$(dirname "$0")
SOFTWARES_DIR="${SOFTWARES_DIR:-$HOME/.softwares}"

SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libiconv-1.17.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/pkg-config-0.29.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/libressl-3.9.2.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/zlib-1.3.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/texinfo-7.1.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/ncurses-6.5.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/setuptools-73.0.0.sh
SOFTWARES_DIR=$SOFTWARES_DIR $BASEDIR/meson-1.5.1.sh