#!/bin/zsh

#!/bin/zsh
set -e
touch $HOME/.zshrc
source $HOME/.zshrc

## No runtime dependencies

## TO BE EDITED ACCORDING TO YOUR PREFERENCES
PROGRAM_VERSION="2024.07.02"
WEB_FILE_VERSION="2024-07-02"
WEB_FILE_NAME="cacert"
PROGRAM_NAME="mozilla-ca"
SHA512_SUM="6c8d96ebedaacaafd3997fb2c5dca7537f64121005efc7084aa97a950e4a53eac1fd640cfe8335e1e32b16253fc7306132f2cefaa588891042653bdaf36ff6c7"

## EDIT WITH CARE
SOFTWARES_DIR="${SOFTWARES_DIR:-$HOME/.softwares}"
SOURCES_DIR="$SOFTWARES_DIR/sources"
BUILD_DIR="$SOFTWARES_DIR/build"
INSTALL_DIR="$SOFTWARES_DIR/install"

## SHOULD NOT BE EDITED
BASE_DIR=$(realpath $(dirname "$0"))
PROGRAM_FULL="$PROGRAM_NAME-$PROGRAM_VERSION"
PROGRAM_INSTALL_PREFIX="$BUILD_DIR/$PROGRAM_FULL"

SOFTWARES_DIR=$SOFTWARES_DIR

if $BASE_DIR/utils/detect-installation.sh "$PROGRAM_NAME" min="$PROGRAM_VERSION" > /dev/null; then
  echo "$PROGRAM_NAME $PROGRAM_VERSION is already installed"
  exit 0
fi

SOFTWARES_DIR=$SOFTWARES_DIR $BASE_DIR/utils/download-file.sh \
  "https://curl.se/ca/$WEB_FILE_NAME-$WEB_FILE_VERSION.pem" \
  "$WEB_FILE_NAME-$WEB_FILE_VERSION.pem" \
  "$SHA512_SUM"
cd $SOURCES_DIR
mkdir $PROGRAM_INSTALL_PREFIX

mv $WEB_FILE_NAME-$WEB_FILE_VERSION.pem $PROGRAM_INSTALL_PREFIX/$WEB_FILE_NAME.pem
if [ -L $INSTALL_DIR/$PROGRAM_NAME ]; then
    rm $INSTALL_DIR/$PROGRAM_NAME
fi
ln -s ../build/$PROGRAM_FULL $INSTALL_DIR/$PROGRAM_NAME